#!/usr/bin/env bash
# Script to check subdomains and their DNS records

audit_subdomain() {
  local domain="$1"
  local subdomain="$2"
  local record_type
  local destination

  if [ -n "$subdomain" ]; then
    subdomains=("$subdomain")
  else
    subdomains=("www" "lb-01" "web-01" "web-02")
  fi

  for sub in "${subdomains[@]}"; do
    result=$(dig +short "$sub.$domain")
    if [ -n "$result" ]; then
      record_type=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $4}')
      destination=$(dig "$sub.$domain" | grep -A1 'ANSWER SECTION:' | awk 'FNR == 2 {print $5}')
      echo "The subdomain $sub is a $record_type record and points to $destination"
    else
      echo "The subdomain $sub does not point to your $sub server IP"
    fi
  done
}

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 <domain> [subdomain]"
  exit 1
fi

domain="$1"
subdomain="$2"
audit_subdomain "$domain" "$subdomain"
