#!/usr/bin/env bash
# Script that does dank memes

answer() {
  domain="$1"
  subdomains=("www" "lb-01" "web-01" "web-02")

  for subdomain in "${subdomains[@]}"; do
    result=$(dig "$subdomain.$domain" +short)
    if [ -n "$result" ]; then
      echo "Your subdomain $subdomain points to your $subdomain server IP"
    else
      echo "Your subdomain $subdomain does not point to your $subdomain server IP"
    fi
  done
}

if [ "$#" -eq 1 ]; then
  answer "$1"
fi
