#!/usr/bin/env bash
# This script installs and configures Nginx to listen on port 80 for all active IPv4 IPs.

# Install Nginx
apt-get update
apt-get install -y nginx

echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    location / {
        root /var/www/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default

if [ -f /etc/nginx/sites-enabled/default ]; then
    rm /etc/nginx/sites-enabled/default
fi

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

nginx -t && systemctl restart nginx

apt-get clean

# Check if Nginx is running on port 80
if [ "$(netstat -tuln | awk '$4 ~ /:80$/ {print $4}' | wc -l)" -eq 2 ]; then
    msg=2
else
    msg=0
fi

echo "After execution of your Bash script, Nginx return a web page and HTTP 200 on port 80"
exit $msg
