#!/usr/bin/env bash
# This is the init script to manage manage_my_process.
function start_manage_my_process
{
  if [ -f "/var/run/my_process.pid" ]; then
    echo "manage_my_process is already running."
  else
    nohup ./manage_my_process >/dev/null 2>&1 &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
  fi
}
function stop_manage_my_process
{
  if [ -f "/var/run/my_process.pid" ]; then
    pid=$(cat /var/run/my_process.pid)
    kill "$pid"
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running."
  fi
}
function restart_manage_my_process
{
  stop_manage_my_process
  start_manage_my_process
  echo "manage_my_process restarted"
}
case "$1" in
  start)
    start_manage_my_process
    ;;
  stop)
    stop_manage_my_process
    ;;
  restart)
    restart_manage_my_process
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
