#!/usr/bin/env bash
# This script displays the content of the /etc/passwd file in a specific format using a while loop and IFS.
while IFS=: read -r user pass uid gid comment home shell; do
  printf "The user %s is part of the %s gang, lives in %s and rides %s.\nUSER ID's place is protected by the passcode %s, more info about the user here: %s\n\n" "$user" "$(getent group "$gid" | cut -d ':' -f 1)" "$home" "$shell" "$pass" "$comment"
done < /etc/passwd
