#!/usr/bin/env bash
# This script reconfigures Nginx to run as the 'nginx' user and listen on port 8080.

sed -i 's/user  nginx;/user  nginx;/' /etc/nginx/nginx.conf

sed -i 's/listen       80;/listen       8080;/' /etc/nginx/conf.d/default.conf

chown -R nginx:nginx /var/lib/nginx

service nginx restart

ps auxff | grep ngin[x]
nc -z 0 8080
