#!/usr/bin/env bash
sed -i 's/user  nginx;/user  nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen       80;/listen       8080;/' /etc/nginx/conf.d/default.conf
chown -R nginx:nginx /var/lib/nginx
service nginx restart
ps auxff | grep ngin[x]
nc -z 0 8080
